language: csharp
mono: none
dotnet: 2.1.300
script:
  - dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v\d+.\d+.\d+$"
  script: bash .deploy.sh
