name: Publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack -c Release --no-restore --include-symbols -o build
    - name: Upload artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: release
        path: build
    - name: Push to nuget.org
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push "build/AzZipGo.*.symbols.nupkg" -s "https://api.nuget.org/v3/index.json" -k "$NUGET_API_KEY"
